### ISSUE TITLE
Discord OAuth Bug

### ISSUE THREAD

**Issue by jindalpriyanshu101** [Qwaekactyl/Qwaekactyl#11]
Hi there, i've noticed a critical bug.

first of all, make the [documentation](https://docs.qwaekactyl.xyz/docs/intro) more specific and to the point, since its missing some critical points for Discord OAuth setup.

<img width="562" alt="image" src="https://user-images.githubusercontent.com/52918255/231268642-76de831c-aef6-43ae-beda-53bcbb5340a7.png">

Here, if you notice, there's absolutely no information on what to put inside **Redirect URI** on https://discord.dev application, which i have figured out, its `yourdomain/callback` (for example, https://qwaekactyl.com/callback)

**Here comes the main point**, after setting these things up and authorizing our discord id with the application, it redirects us to "https://example.com/callback?code=xyz" instead of "http://example.com:7777/callback?code=xyz"

And since ssl works only for `example.com` and not `example.com:7777` its not feasible to use https connection for domain:port, which makes it to return a insecure connection warning. Henceforth please fix the redirecting after authorizing our discord account with the discord application.

**Comment by jindalpriyanshu101** [comment]
More information;

- Discord OAuth will not work if you put `http://example.com:7777/callback` instead of `https://example.com/callback`, in-case you're thinking about changing the redirect URI on discord.dev
- You can verify these things at my test portal, http://dashboard.elementix.tech:7777

**Comment by ItzCrazyKns** [comment]
Hey JindalPriyanshu,

Regarding the SSL setup and the need for an NGINX reverse proxy server to achieve it.

Regarding the missing information on what to put inside the Redirect URI field on the Discord application page, you are correct that it should be your domain followed by the callback endpoint. For example, if your domain is "example.com" and your callback endpoint is `/callback`, the Redirect URI should be `https://example.com/callback`.

Now, regarding the issue with the redirection after authorizing the Discord account with the application, it's important to note that the server-side code is not responsible for the redirection. The Discord API handles the redirection automatically, and it's up to the developer to configure the Redirect URI correctly on the Discord application page.

If the redirection is going to `https://example.com/callback?code=xyz` instead of `http://example.com:7777/callback?code=xyz`, it's likely because the Redirect URI was not configured correctly on the Discord application page. You should double-check that the Redirect URI is set to the correct domain and port.
